### ISSUE TITLE
Command `run-desktop` unrecognized. (after following Getting Started)

### ISSUE THREAD

**Issue by msh2050** [status-im/react-native-desktop#268]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yse

### Environment

Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/status-im/react-native-desktop#master => 0.55.4

### Steps to Reproduce

(Write your steps here:)

1. Just fallow the steps in Getting Started(Install Prerequisites , Install adjusted react-native-cli and Create new App)

### Expected Behavior

I just expect a hello world screen will run  
### Actual Behavior

after give the command (  >react-native desktop)
I get the following error (

> exec error: Error: Command failed: pwd && patch --verbose -d ./node_modules/metro/src/JSTransformer -i ../../../react-native/increase_bundler_memory_usage.patch
> 'pwd' is not recognized as an internal or external command,
> operable program or batch file.

) 
then:

>  Command `run-desktop` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

please find the below attached cmd script from start to end. note how the command "info" and  help changing after the command (  >react-native desktop)

[cmdscript.txt](https://github.com/status-im/react-native-desktop/files/2124362/cmdscript.txt)
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by madhavarshney** [comment]
> removed 1212 packages and updated 18 packages in 15.2s

Seems like all the packages got removed when running `react-native desktop`.  This is probably due to `react-native init` using yarn to bootstrap the project and then `react-native desktop` running an install command with npm, which removes all the other packages.  Can you run `yarn`/`yarn install` in the project and try again?

**Comment by vkjr** [comment]
@msh2050, thank you for reporting.

>'pwd' is not recognized as an internal or external command,
'pwd' is not a Windows command. 
I think`react-native-desktop/local-cli/desktop/genDesktop.js` should be modified to make patching cross-platform to resolve this issue.

**Comment by msh2050** [comment]
I get this error:
```
Command failed: build.bat -g "MinGW Makefiles"
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/Program Files/Git/usr/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.

Call Stack (most recent call first):
  CMakeLists.txt


CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage 
```

**Comment by MaxRis** [comment]
@msh2050 to not receive this CMake error you really need to remove sh.exe from the PATH. Haven't investigated if some another solution exists.

**Comment by MaxRis** [comment]
@msh2050 for some reasons metro package haven't updated with our patch (it should get updated on `npm install`) ... Maybe, because you have used yarn?

You should patch it manually https://github.com/status-im/react-native-desktop/blob/master/patches/metro%2B0.30.2.patch#L20
File `node_modules/metro/src/defaults.js` and line: 
```
exports.platforms = ['ios', 'android', 'windows', 'web'];
```
should be extended with "desktop" platform

**Comment by msh2050** [comment]
🌷🌹thanks @MaxRis @madhavarshney
I will start enjoying the universal platform programming 😉

**Comment by madhavarshney** [comment]
@msh2050 - Glad to hear that worked for you 😄 .  Just some notes:

> I change the file name of sh.exe .

While it shouldn't, doing so may have unintended side-effects with Git.  A safer option is to follow https://github.com/status-im/react-native-desktop/issues/268#issuecomment-399257480 and remove `C:\Program Files\Git\bin`, `C:\Program Files\Git\usr\bin`, etc. from your path and just leave `C:\Program Files\Git\cmd` for invoking git from cmd or Powershell.  Unless you use tools provided by Git such as `awk.exe` in cmd or Powershell (not through Git bash), this should not cause a problem.

> then to solve the (CMake was unable to find a build program corresponding to "MinGW Makefiles" ) ..... copy/rename mingw32-make.exe to make.exe.

I don't think that should be necessary if you add both `C:\<Qt Installation>\Tools\mingw530_32\bin` and `C:\<Qt Installation>\5.9.1\mingw53_32\bin` to your path.

> for some reasons metro package haven't updated with our patch (it should get updated on npm install) ... Maybe, because you have used yarn?

@MaxRis - No, this is because the `prepare` script only runs when `npm install` or `yarn` is [run locally](https://docs.npmjs.com/misc/scripts).  For patching with `npm install` / `yarn` on the consumer's end, a `postinstall` script will need to be added with patch-package, but I don't know if patch-package works for packages being installed instead of running locally.  A better option is modifying rn-cli.config.js as I wrote in https://github.com/status-im/react-native-desktop/issues/245#issuecomment-395483506.
