### ISSUE TITLE
Hyperlinks should open a default browser window

### ISSUE THREAD

**Issue by siphiuel** [status-im/react-native-desktop#278]
Currently, there is no way to open a default browser window from within RN-desktop app. The underlying Qt functionality (e.g. perhaps `QDesktopServices::openUrl` googled [here](https://stackoverflow.com/questions/10250332/how-to-open-a-link-in-a-default-user-browser-in-qt)) should be available.

**Comment by vkjr** [comment]
@siphiuel, I added react-native functionality to open specified url in a default browser. But it doesn't make hyperlinks in `Text` component to be highlighted and clickable. 
If we need only Linking.openURL(), then we probably should update header of this issue, because this functionality not related to hyperlinks.
If we need URLs to be clickable in the text, then description should be changed :)
