### ISSUE TITLE
Packaging a react-native-desktop app

### ISSUE THREAD

**Issue by giacomocerquone** [status-im/react-native-desktop#449]
Hi everyone. I've seen #429 and from that issue it seems like it's already possible to package a rn desktop app, is that so? If yes, are here some short guidelines on how to do that?
I need to execute a rn app on windows and I've to understand if this is a feasible way (already tried with react-native-windows, but they're uwp apps and don't really feel like native).

**Comment by vkjr** [comment]
Hi @giacomocerquone!
Right now packaging isn't documented. And it is not very straightforward.
During development `node ubuntu-server.js` should run on dev machine because it provides js environment to evaluate all js code.
In production we don't want to force user to install node, so in [status-react](https://github.com/status-im/status-react) project we made `ubuntu-server.js` a binary that runs along app when started.
That is not ideal solution, because package significantly increases in size (+100mb).
Right now we work on embedding js engine inside `react-native-desktop` and getting rid of node dependency. When it is finished, there will be more convenient way to package apps. And documentation will be written :)

**Comment by giacomocerquone** [comment]
Perfect, thank you very much for your work and your exhaustive explanation :)

**Comment by gK347** [comment]
@vkjr Can you help me with packaging app for windows? I know its not that easy as of this point but still if possible you can help me to create windows packaging. It is ok for me if application size is larger than 100mb.

**Comment by vkjr** [comment]
@gK347, ok, I'll try to create a document describing all steps and will add it to repo.

If this is not a secret, what kind of app you are developing with `react-native-desktop`?

Hope to see your project here soon - https://github.com/status-im/react-native-desktop/blob/master/docs/AppsUsingRnd.md

**Comment by gK347** [comment]
> @gK347, ok, I'll try to create a document describing all steps and will add it to repo.
> 
> If this is not a secret, what kind of app you are developing with `react-native-desktop`?
> 
> Hope to see your project here soon - https://github.com/status-im/react-native-desktop/blob/master/docs/AppsUsingRnd.md
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/11767950?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[status-im/react-native-desktop](https://github.com/status-im/react-native-desktop)**A Desktop port of React Native, driven by Qt, forked from Canonical - status-im/react-native-desktop

I am doing it for learning purpose.
