### ISSUE TITLE
Is Mac and Windows support necessary?

### ISSUE THREAD

**Issue by jor1196** [status-im/react-native-desktop#468]
Windows already has the support to React Native provided by the company that is behind it
https://github.com/Microsoft/react-native-windows

And someone else already supports Mac
https://github.com/ptmt/react-native-macos

Why not just focus on just supporting Linux? Thus they save efforts and allocate resources to Linux that urgently needs applications

**Comment by athif23** [comment]
I didn't know those repos exists, thanks for the info.

**Comment by vkjr** [comment]
@jor1196, the goal is to have single implementation that will behave the same way on all platforms.
Due to the crossplatform nature of Qt platforms support doesn't take much time in comparison with actual development.

**Comment by achipa** [comment]
React Native Windows is currently largely a C# .NET affair. If you have any Qt experience and/or Qt code (or prefer C++), a Qt back-end is a huge asset for those of us needing to interface with a lot of native modules in a cross-platform way via Qt.

To put it another way, Qt itself should not drop Windows support just because Microsoft has it's own UI/platform toolkits :)
