### ISSUE TITLE
ubuntu-server via pipe

### ISSUE THREAD

**Issue by farwayer** [status-im/react-native-desktop#93]
Hi. Nice to see someone making this crazy porting! Good luck!
One question: how do you run examples via pipe? Current ubuntu-server realization don't work via http :(

**Comment by vkjr** [comment]
@farwayer, thanks!
Usually we don't run examples via pipe and work with http. Could you please provide more details on how do you run examples and what errors do you get?
Thanks.

**Comment by farwayer** [comment]
Sorry for bothering. I did it wrong. One small question: what is purpose of `ubuntu-server.js`?

**Comment by vkjr** [comment]
@farwayer, it executes javascript code of react native application.

**Comment by farwayer** [comment]
@vkjr Thanks!

**Comment by MaxRis** [comment]
Reopening the issue, since communication with node process via pipe doesn't work and probably should be fixed.
Some details of the issue:
- Bridge should be configured with PipeExecutor to communicate with node process via pipe.
- It seems at least reading from QProcess std output inside PipeExecutor has issues with data block size calculation. For example, node process sends data block with size on the start of data block "8425" , but  PipeExecutor for some reasons reads the 4Bytes size of next data block as "875770417". The issue happens permanently, but only after previous block with text message "null" (this might be not related to reason of issue).

**Comment by MaxRis** [comment]
Have pushed changes to debug PipeExecutor and JS data transfer into branch https://github.com/MaxRis/react-native-qt/tree/bug/pipe-executor-broken-%2393 to be revisited later
- ubuntu-server.js should be in the root build directory ( or file is not found by node process issue will be returned by node process )
- Data transfer process via pipe should be investigated. If transfer of data happens only when writer is writing and reader is reading and additionally pipe's buffer is not full, current implementation should be possibly changed.
